### ISSUE TITLE
not a bug most likly

### ISSUE THREAD

**Issue by GamearooCodes** [Erabior/RouteManager#28]
when you escape the game and resume i think it shoul,d pull from a last state of what settings you had it at so we dont have to resetup every time we rejoin the game

**Comment by Erabior** [comment]
This is intentional behavior. the coroutine is terminated on map unload to avoid duplicate coroutines. Saving orders is possible and based on discussions with another modder should be possible by saving within the base game's save code. but for now, you will have to re-enable and re-set the orders every time you load the game for safety reasons.
