### ISSUE TITLE
Route Mode Not Handling Terminus Stations Properly (issues with Alarka Jct)

### ISSUE THREAD

**Issue by Erabior** [Erabior/RouteManager#3]
Under Investigation. If you observe this behavior please provide any information here.

**Comment by hjp766** [comment]
Seeing something similar currently (Whittier - Alarka Jct). The Alarka Jct end I suspect may be linked to the other issue, so will see if it resolves on expansion completion to Alarka. At Whittier, I am having to manually start the train away and then select road mode.

**Comment by hjp766** [comment]
Repeating here so visible.

This is the Whittier turnaround. It seems to be problematic with the engine at the Sylva end in that it cannot pull up close enough to the home signal when it is on. https://www.dropbox.com/scl/fi/1nzoq1wwwciq2ny0akbuq/MedalTVScreenRecording20231222153547.mkv?rlkey=7xz2ynsli8rx7kaiscx3bgsvv&dl=0 
Still trying to capture the Alarka Jct stopping distance issue (I think it is clearing the mainline track circuit whilst not clearing the junction so giving a false clear on CTC)

**Comment by hjp766** [comment]
This is the stopping issue at Alarka Jct (again Loco at Sylva end) does not clear main, generates false clear on CTC, then runs back without being signalled potential head on conflict.
https://www.dropbox.com/scl/fi/oqenrg53mlq4ijtllb6a5/MedalTVScreenRecording20231222160242.mkv?rlkey=av24kdm6xd9ek0crok4r126sn&dl=0

I will now reverse the consists to have the loco at the other end as I think that solved it with brief testing yesterday.

**Comment by hjp766** [comment]
Alarka is solved by reversing the consist. Just whittier left to try. https://www.dropbox.com/scl/fi/lj1i9kkdw4ps3p2uvg70y/MedalTVScreenRecording20231222164152.mkv?rlkey=96y51ncgebb5ryy7cfrgenulr&dl=0

**Comment by hjp766** [comment]
Final vid. Whittier with consist reversed (loco at Bryson end) and the problem has vanished.

https://www.dropbox.com/scl/fi/lgu4pmqistvvfkg76yhfo/MedalTVScreenRecording20231222170918.mkv?rlkey=n4grausqwa84uj61729lv7nwf&dl=0

**Comment by Erabior** [comment]
i apologize but there does not seem to be audio with these, are you saying the issue is fixed? The one thing i will say is the mod was tested without signals only because the way the signals and CTC system are modeled in the game is not *exactly* how they work in real life and that has lead to a few issues that i have had to try to work around as well as one of the other modders that is essentially my modding Sensai has complained about on several occasions. If the issue has not been fixed by any of the updates then do your best to leave track segments that your passenger line is running on cleared in CTC. The Road AI should properly detect when a segment is occupied by another consist and act accordingly.

**Comment by hjp766** [comment]
I believe so (without totally reworking stopping points). The work around is to run with the loco always at the Andrews (Down in UK parlance, i.e. away from MP 0). This alleviates the weirdness at both Whittier and Alarka Jct. Doing this at Whittier it reverses properly, and at Alarka Jct it clears the junction track circuit and the intersection so is subject to positive signal control for departure.

The first two videos show the issues of running with the loco at the Up end towards MP 0 where due to the AI programmed stopping distance from the signal (in the Whittier case) or where the mod has to stop the consist (in the Alarka Jct case) it was causing niggles, but nothing that cannot be worked around by reversing the consist. See videos 3 & 4.

**Comment by Erabior** [comment]
in that case ill close this issue for now
