### ISSUE TITLE
Request: max speed control

### ISSUE THREAD

**Issue by Voidheartd** [Erabior/RouteManager#30]
It'd be very nice to be able to control the max speed. My passenger train wastes a ton of water trying to reach 35mph when it can't. I think it sits around 32mph on part of the way from Bryson to Ela for example, with the throttle at 100%. Also I like to keep the trains at 30 anyway so they aren't having to speed back up after every curve.

**Comment by AdamC1228** [comment]
This should theoretically be possible by adding the slider back to the main panel while route mode is engaged and instead of defining RMMaxSpeed = 100 or (LocoTelem.RRMaxSpeed[Loco] = 100 v2 dev pull request) for the transit cycle of the auto-engineer subroutine we query the value of the slider and use its value instead of 100. 

The problem will be in the utilization of the game UI. Currently the Car inspector has a finite amount of space which is why i suspect the slider was removed. That would allow for more room for the station selection to occur. Although it should be implementable, unless Erabior has a different opinion, i suspect it may not get implemented until a more refined UI can be crafted.

**Comment by Erabior** [comment]
> It'd be very nice to be able to control the max speed. My passenger train wastes a ton of water trying to reach 35mph when it can't. I think it sits around 32mph on part of the way from Bryson to Ela for example, with the throttle at 100%. Also I like to keep the trains at 30 anyway so they aren't having to speed back up after every curve.



> This should theoretically be possible by adding the slider back to the main panel while route mode is engaged and instead of defining RMMaxSpeed = 100 or (LocoTelem.RRMaxSpeed[Loco] = 100 v2 dev pull request) for the transit cycle of the auto-engineer subroutine we query the value of the slider and use its value instead of 100.
> 
> The problem will be in the utilization of the game UI. Currently the Car inspector has a finite amount of space which is why i suspect the slider was removed. That would allow for more room for the station selection to occur. Although it should be implementable, unless Erabior has a different opinion, i suspect it may not get implemented until a more refined UI can be crafted.

This exactly. There is a vertical spacer that is added to always ensure the status of the road AI is put at the bottom of the window which drastically limits the amount of stations that can be displayed at any one time. I removed the direction buttons and speed sliders to increase the number of visible stations. Once the new UI is implemented the speed slider will return. I do not however see any point to add the direction buttons back as they would be useless when route mode is enabled, and they come back immediatley when route mode is disabled anyway.

**Comment by Erabior** [comment]
now that there is a discussions tab, Im going to close this as an issue. Please feel free to put any and all suggestions in the discussions tab
