### ISSUE TITLE
[2.0 Alpha] No UI presented to activate RouteManager.

### ISSUE THREAD

**Issue by celendis** [Erabior/RouteManager#60]
After the Railroader update to 2023.3.2, there is no UI presented to activate the RouteManager features. This affects (at least) RouteManager versions 1.0.2.1 and 2.0 Alpha 1.

Troubleshooting steps taken:
1. Deleted Railroader directory and reinstalled the latest version (2023.3.2) from Steam.
2. Installed BepInEx x64 5.4.22.0
3. Launched Railroader once and exited.
4. Placed RouteManager 2.0 Alpha 1 dll in the plugins folder.
5. Changed BepInEx.cfg LogChannels to All.
6. Launched Railroader and loaded my save game. After loading, selected the passenger train and found no way to activate RouteManager.

Attached are the log files and the save file (in .zip).
[LogOutput.log](https://github.com/Erabior/RouteManager/files/13826743/LogOutput.log)
[Player.log](https://github.com/Erabior/RouteManager/files/13826746/Player.log)
[BlueRidge.zip](https://github.com/Erabior/RouteManager/files/13826749/BlueRidge.zip)

I also created a new sandbox save and found no GUI there.

**Comment by AdamC1228** [comment]
Please revert your changes to BepLnEx.cfg and test again as it would appear that your log files are incomplete. I would like to start with known good settings and the default settings work from my experience. Please test again with the latest 1.x release of route manager. 

- With 1.x installed, create a consist consisting of 1 locomtive and 1 passenger coach
- Click on the locomotive and select it so that its controls are visible. 
- Then click on the orders tab
- Then click the Road button
- Now you will see a checkbox for Enable Route Mode
- Before clicking enable Route Mode you must (yes it is scrollable) select stations for the AI to travel to.



Note: Alpha builds are not meant for general use. They are meant as first look at major changes and are for those wishing to report bugs / provide feedback for upcoming releases or are for targeted testing for open issues.

**Comment by celendis** [comment]
Thank you for your response. However, this occurs with any version of RouteManager that I have attempted to use. 

I did follow your instructions and created a consist of one ten-wheeler and one coach. The "Enable Route Mode" never appears.

As for the log incompleteness, I do not know what else to do. When I do not set it to All, the log files are even more incomplete. 
[LogOutput.log](https://github.com/Erabior/RouteManager/files/13827064/LogOutput.log)
[Player.log](https://github.com/Erabior/RouteManager/files/13827069/Player.log)

I think I will have to make a video just to demonstrate that the option simply doesn't appear for me, even when the log file shows that it did patch the UI interface.

**Comment by celendis** [comment]
I was able to resolve the issue by uninstalling Railroader, disabling steam saves, deleting the Giraffe Lab LLC folder from LocalLow, then reinstalling all as above. I truly do not know what else might be different, but I can only assume something was corrupted, since I noticed that I also did not see the Pullman 1900 open platform in the sandbox passenger car list until I did this complete wipe-out.  Thanks for your patience, but this issue was not with your mod.
