### ISSUE TITLE
V2.0.0.6 - BeepIn - Invalid low fuel warning; fuel is not low

### ISSUE THREAD

**Issue by mlewelt** [Erabior/RouteManager#89]
I wanted to start a trip with my a-26 atlantic with 5t of coal remaining, which is more than enough for the whole trip. Route Manager gives me the low on coal warning and doesnt go. In the .ini low fuel level is set to 0.5t. The same thing happens when using V2 Alpha.

.log and a screenshot is attached.

![routeManger](https://github.com/Erabior/RouteManager/assets/3612152/c80c08ca-9d4f-44ee-9719-7e029a8acb44)

[Player.log](https://github.com/Erabior/RouteManager/files/13954379/Player.log)

**Comment by AdamC1228** [comment]
Please share the .ini config that you are using.

**Comment by mlewelt** [comment]
It is the .ini that comes with the mod, unchanged. I put it in the plugins folder together with the mod .dll, hope that is correct.

[RouteManager.txt](https://github.com/Erabior/RouteManager/files/13962142/RouteManager.txt)

**Comment by AdamC1228** [comment]
I will investigate but in the mean time you can set the value to 0 to disable the coal fuel check.

**Comment by AdamC1228** [comment]
@mlewelt I have tested and I can only reproduce the issues describe here by using 0,5 (0 comma 5) instead of 0.5 (0 point 5) but the logs you provided don't quite match the output I am seeing when using the comma. Did you upload the actual .ini file or did you copy and paste the contents from your file into a text file and upload it? Using the exact file you uploaded results in the correct behavior of warning when less than 0.5 tons of coal.

**Comment by mlewelt** [comment]
I saved the .ini file as .txt and uploaded that since github gave me an error when trying tu upload the .ini file (unsupported file type). I will keep an eye on this and report if this happens again. Havent had the chance to play much since.

**Comment by AdamC1228** [comment]
> I saved the .ini file as .txt and uploaded that since github gave me an error when trying tu upload the .ini file (unsupported file type). I will keep an eye on this and report if this happens again. Havent had the chance to play much since.

I discussed this with armyf35 and they made an excellent point. It looks like parts of the file paths in your logs are in German. Would we be correct to assume that your computer is configured for the German language-pack?

If so, we suspect this is because apparently stems from the German formatting of numbers having the comma and period swapped  for numbers as apposed to the expected format that say America uses. If that is what is happening then we will have to make accommodations to handle that for Germany and other locations that use the alternate format.

**Comment by mlewelt** [comment]
Yes that is correct, Windows (and Steam) is set to german on my pc. We do use comma instead of period for the decimal separation but i dont see how this would affect a value that is read directly from an .ini? Ofc you guys know more than me on how this could indeed be a problem.

**Comment by AdamC1228** [comment]
Please try the modification below to see if this corrects the issue. Please leave the ini file as is when testing.

As for your question, numbers in files are stored as text and when read from the file, they are treated as text until we "convert them to a number." When converting we have to do something we call parsing which is a fancy way of converting things. When parsing, the code will take certain cues from the system to know how to convert "0.5" to a number and since in German the period is not a decimal separator 0.5 is read as 05 which equates to 5. It can be a bit confusing but in the end we just have to either tell the computer to ignore the system format and default to en-us formats or we take steps to be culture aware and allow & appropriately handle alternate formats. 
 
Either way, give this specific build a shot and post back one of your log files please. 

[RouteManager.BepInEx 2.0.0.6_invariant.zip](https://github.com/Erabior/RouteManager/files/13996315/RouteManager.BepInEx.2.0.0.6_invariant.zip)

**Comment by mlewelt** [comment]
Just tested the new version with the old unchanged .ini and the bug seems fixed. With 4.8 tonnes of coal left route manager has the correct behaviour and starts the train. In case this is relevant i did this testing on a different save (Sandbox), but with the old version the bug occured the same way it did originally.

[Player.log](https://github.com/Erabior/RouteManager/files/13998848/Player.log)

**Comment by AdamC1228** [comment]
Good, I am going to mark this as closed and I will post an official hotfix later today.
